version: 2

executors:
  ubuntu_machine:
    machine:
      image: ubuntu-2004:202010-01

commands:
  git-pull:
    description: "Update git repository from the virtual machines"
    steps:
      - run: |
          ssh -4 -L 9001:10.10.28.78:22 -Nf jfollert@ssh2.inf.utfsm.cl
          ssh -p 9001 sd@127.0.0.1 "cd go/src/github.com/jfomu/DNSDistribuido && git pull"

jobs:
  executor: ubuntu_machine
  deploy_to_vm:
     steps:
      - add_ssh_keys:
            fingerprints:
              - "b3:0f:e7:d4:98:21:40:e2:18:2a:b6:b9:09:5b:1d:fe"
      - checkout
      - git-pull


workflows:
  deploy:
    jobs:
      - deploy_to_vm: